Create ez_35.mdx
comcode-org/hackmud_wiki pull request #102
Opened 2023-12-21 04:11 UTC by kbinreallife

2023-12-21 05:33 UTC, Fayti1703 requested changes

2023-12-21 05:33 UTC, Fayti1703 commented on docs/upgrades/locks/ez_35.mdx
> +  <summary>Spoilers for ez_35's solutions.</summary>
This summary doesn't appear properly. (Unfortunately I don't know why)

2023-12-21 05:45 UTC, Fayti1703 requested changes

2023-12-21 05:45 UTC, Fayti1703 commented on docs/upgrades/locks/ez_35.mdx
> +  second parameter is a single digit, input as a number, ranging from 0 to 9.
Add some newlines here to break the paragraph correctly, which fixes the summary thing

```suggestion
  <summary>Spoilers for ez_35's solutions.</summary>
  
  The first parameter's possible strings are, "open", "unlock", and "release". The
  second parameter is a single digit, input as a number, ranging from 0 to 9.
  
```

2023-12-21 05:45 UTC, Fayti1703 commented on docs/upgrades/locks/ez_35.mdx
> +>>user.fakeloc123 \{ ez_35: "open", digit: 0 }
Remove the backslash here, it shows up in the output.
```suggestion
>>user.fakeloc123 { ez_35: "open", digit: 0 }
```

2023-12-29 06:06 UTC, kbinreallife commented
prettier is sometimes adding > > where they don't need to be, and is sometimes spacing out ones that exist. it is also adding additional triple (and in some silly cases, quadruple) backticks at the end of the page.

2023-12-30 07:26 UTC, Fayti1703 approved these changes

2023-12-30 07:42 UTC, merged