Create accts.transactions.mdx
comcode-org/hackmud_wiki pull request #145
Opened 2024-01-04 21:48 UTC by kbinreallife

2024-01-05 07:34 UTC, ghambhackmud requested changes
Suggested changes that bring document inline with template.

Also suggested some wording changes, some keeping the previous style of the article.

2024-01-05 07:34 UTC, ghambhackmud commented on docs/scripting/trust scripts/accts.transactions.mdx
> +On the Command Line Interface:
```suggestion
### CLI
```

Brings inline with template

2024-01-05 07:34 UTC, ghambhackmud commented on docs/scripting/trust scripts/accts.transactions.mdx
> +As a subscript:
```suggestion
### Script
```

Brings inline with template

2024-01-05 07:34 UTC, ghambhackmud commented on docs/scripting/trust scripts/accts.transactions.mdx
> +The 'start' argument can be used in combination with 'count', or on it's own, to offset the beginning of the list to the desired position.
```suggestion
The 'start' argument offsets the beginning of the list of transactions to the desired position. Can be used in combination with 'count'.
```

2024-01-05 07:34 UTC, ghambhackmud commented on docs/scripting/trust scripts/accts.transactions.mdx
> +The 'start' argument can be used in combination with 'count', or on it's own, to offset the beginning of the list to the desired position.
Maybe less confusing wording?

2024-01-05 07:34 UTC, ghambhackmud commented on docs/scripting/trust scripts/accts.transactions.mdx
> +A user may filter transactions that are sent to a specific username.
```suggestion
The 'to' argument filters transactions that are sent to a specific username.
```

2024-01-05 07:34 UTC, ghambhackmud commented on docs/scripting/trust scripts/accts.transactions.mdx
> +A user may filter transactions that are sent from a specific username.
```suggestion
The 'from' argument filters transactions that are sent from a specific username.
```

2024-01-05 07:34 UTC, ghambhackmud commented on docs/scripting/trust scripts/accts.transactions.mdx
> +A user may filter transactions by the specific script which sent them.
```suggestion
The 'script' argument filters transactions by the specific script which sent them.
```

2024-01-06 21:08 UTC, ghambhackmud approved these changes
Looks good

2024-01-06 21:11 UTC, ghambhackmud approved these changes
Looks good

2024-01-06 21:19 UTC, Fayti1703 approved these changes
Not sure if we'd want to mention how the special-sauce output produced in CLI-mode works (which is what you get with `is_script: false`)

2024-01-06 21:26 UTC, merged