Add acct_nt (T2 Lock)
comcode-org/hackmud_wiki pull request #463
Opened 2024-05-10 22:31 UTC by MichaelEpicA

Adds a full description and explanation of every mode and every way acct_nt can behave.

### Problem

Fixes #461

2024-05-11 01:55 UTC, Zachava96 requested changes
All articles should be written in third person with no referential nouns (e.g. you, your), except for Tutorials, FAQs, and Writeups.

2024-05-11 01:55 UTC, Zachava96 commented on acct_nt.mdx
> +Look at the timestamps that acct_nt gives you, and add up all the transactions from the starting timestamp to the end. The actual starting and ending timestamps may be a bit off from what acct_nt giv
All articles should be written in third person with no referential nouns (e.g. you, your), except for Tutorials, FAQs, and Writeups.

```suggestion
Add up all the transactions between the two timestamps, with incoming transactions being positive and outgoing transactions being negative. The actual starting and ending timestamps may be incorrect by up to one minute.
```

2024-05-11 01:55 UTC, Zachava96 commented on acct_nt.mdx
> +Look at the timestamps that acct_nt gives you, and add up all the transactions where you gained money from the starting timestamp to the end. The actual starting and ending timestamps may be a bit of
```suggestion
Add up all the incoming transactions between the two timestamps. The actual starting and ending timestamps may be incorrect by up to one minute.
```

2024-05-11 01:55 UTC, Zachava96 commented on acct_nt.mdx
> +Look at the timestamps that acct_nt gives you, and add up all the transactions where you lost money from the starting timestamp to the end. The actual starting and ending timestamps may be a bit off
```suggestion
Add up all the outgoing transactions between the two timestamps. The actual starting and ending timestamps may be incorrect by up to one minute.
```

2024-05-11 01:55 UTC, Zachava96 commented on acct_nt.mdx
> +With or without memos indicates whether or not if you should consider transactions with memos. If it says with memos, make sure the transactions have memos before adding them, otherwise ignore them.
```suggestion
Indicates whether only transactions with (or without) memos should be considered.
```

2024-05-11 01:55 UTC, Zachava96 commented on acct_nt.mdx
> +Memos are a little message that can be sent with a transaction. It displays as memo: "message here" in [[accts.transactions]].
I don't think that memos need to be explained here; if needed, they can be explained on the accts.transactions page.
```suggestion
```

2024-05-13 00:10 UTC, Zachava96 approved these changes

2024-05-14 11:18 UTC, Zachava96 requested changes
Total spent/earned actually uses net, not just incoming or outgoing, my bad

2024-05-15 17:38 UTC, MichaelEpicA commented on acct_nt.mdx
> +Add up all the outgoing transactions between the two timestamps. The actual starting and ending timestamps may be incorrect by up to one minute.
Are you sure they use net? That just seems like a redundant thing then, and it should probably just be put under one category.

2024-05-16 10:07 UTC, hmdunce commented
Thanks both of you! I was going to see about merging but looks like there is still discussion.

I think it doesn't have to be perfect. Someone can always fix it later.

2024-05-16 10:09 UTC, hmdunce requested changes
The file should be moved to docs/upgrades/locks so that it shows up in the locks list. Currently the page doesn't show up at all I think.

You can do it with
```
git mv acct_nt.mdx docs/upgrades/locks/
```
and then commit, push as usual.

I would just do this but I don't want to cause confusion for ongoing work on the file.

2024-05-16 10:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/comcode-org/hackmud_wiki?pullRequest=463) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/comcode-org/hackmud_wiki?pullRequest=463) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: MichaelEpicA<br/>:x: hmdunce<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/comcode-org/hackmud_wiki?pullRequest=463) it.</sub>

2024-05-16 13:17 UTC, hmdunce approved these changes
OK, I checked in codespaces and it looks good to me.

I am not checking for 100% accuracy since I don't think I've ever fully understood how acct_nt works, but I think that's fine.

I only have one question: do the stats and behavior sections contain spoilers? I've seen the README definition but I'm not sure exactly what it means. :smile:

I don't know how much it matters though.

2024-05-16 13:41 UTC, hmdunce commented
The meaning of `acct_nt_min` in particular does not seem obvious to me. I suspect what is written here may not even be correct??? :man_shrugging:

2024-05-16 13:43 UTC, MichaelEpicA commented
acct_nt_min as close to my understanding is correct, since acct_nt uses a range of transactions and acct_nt_min is how small that range can be

2024-05-16 13:58 UTC, hmdunce commented
Just to be safe, I will add a commit, you can tell me if it looks good to you?

By the way, just curious, are you able to push the "Squash and merge" button when it turns green? I don't know who has permission. If you are able, you should feel free to push it, IMO.

2024-05-16 13:59 UTC, MichaelEpicA commented
I do not have write access so no

2024-05-16 14:08 UTC, hmdunce commented
Ok, it was probably unnecessary, but added some spoiler guards. If it looks good to you I will merge?

Thanks for your contribution!

2024-05-17 03:06 UTC, MichaelEpicA commented
Yep

2024-05-17 19:13 UTC, merged